app:
  image: ibmcom/swift-ubuntu:3.1
  ports:
    - "8080:8080"
  volumes:
    - .:/root/watson-recommendations-api-kitura
  command: bash -c "cd /root/watson-recommendations-api-kitura && swift build --clean && swift build && .build/debug/restaurant-recommendations"
